# install.packages("tidyverse")
# install.packages("rmarkdown")
# install.packages("httr")
# install.packages("shinydashboard")
# install.packages('leaflet')

install.packages("quantmod")
install.packages("Quandl")
install.packages("dynlm")
install.packages("plyr")
install.packages("tsDyn")